NewHaven TFT display driver
Analog-Devices-MSDK/Libraries-miscDrivers pull request #18
Opened 2022-11-04 23:52 UTC by Jake-Carter

Migrated from #9 (No idea why, but Github automatically closed it after I pushed my changes to Victor's fork...)

Only changes I made between #9 and here are:
* https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/commit/3c681c04c6b01804c17c6bfb22d1733dac7b9e76 (add mono display function)
* https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/commit/092b84df4577a2dc13a04858fa7872f4ae498352 (clang-format)
* https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/commit/876ec38b1d1af60c5f864540b0f50f4df8504081 (lint)

Drivers work great.  TFT Demo passes, and I tested mono and color display functions with CameraIF below:

![20221104_181432](https://user-images.githubusercontent.com/38844790/200090252-179c10d0-40ea-4ec6-a37d-7b5114503498.jpg)
(`CAMERA=HM0360_MONO`)

![20221104_183107](https://user-images.githubusercontent.com/38844790/200090254-9e870088-292c-442e-a087-3b096c8b4367.jpg)
(`CAMERA=OV7692`)

2022-11-07 16:17 UTC, lorne-maxim requested changes
Most the changes requested revolve around making these file less board specific.  Ideally, we can move all board specific settings to board.h (or maybe board.mk, but that feels a little less intuitive to me).

2022-11-07 16:17 UTC, lorne-maxim commented on Display/tft_st7789v.c
> +    __disable_irq();
Need to save state of IRQ before disabling it, then only enable it at the end if it was already on.  (This is a common error throughout the SDK that we need to get cleaned up.)

2022-11-07 16:17 UTC, lorne-maxim commented on Display/tft_st7789v.h
> +#if (TARGET_NUM == 78000)
These are board specific options and should be configured in the board files.  Let's keep the miscDrivers as board agnostic as possible.

2022-11-10 23:46 UTC, Jake-Carter commented on Display/tft_st7789v.c
> +    MXC_GPIO_OutClr(TFT_SS_PORT, TFT_SS_PIN);
@lorne-maxim done, SPI transport layer has been moved to the board files.

2022-11-10 23:50 UTC, Jake-Carter commented on Display/tft_st7789v.c
> +    __disable_irq();
Done, see https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/pull/18/commits/e804a9bc41270ef5bf9f2c977291a00c998dad3b

2022-11-10 23:53 UTC, Jake-Carter commented on Display/tft_st7789v.c
> +    (void)format;
Yes, but it is only used by 4 examples across our whole SDK.  Additionally, it isn't used by the AI87 TFT_Demo example.

The only file that implements it is the ssd2119 file, and the implementation is not very clean...

https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/blob/726518622a423cd8fa6a5a7168ced57364dc680a/Display/tft_ssd2119.c#L1286

I think we should address this in a future PR alongside some other TFT standardizations.

2022-11-10 23:54 UTC, Jake-Carter commented on Display/tft_st7789v.c
> +{
Same here, not currently required for the AI87 EVKIT but should be addressed in a future PR

2022-11-11 16:05 UTC, lorne-maxim commented on Display/tft_st7789v.c
> +    (void)format;
Sounds good.  Please create a Jira or GitHub issues with the list of improvements you have in mind.

2022-11-11 16:07 UTC, lorne-maxim approved these changes

2022-11-11 16:20 UTC, merged