Adding ST7735 TFT Controller driver.
Analog-Devices-MSDK/Libraries-miscDrivers pull request #19
Opened 2022-11-09 20:07 UTC by Jacob-Scheiffler

2022-11-10 20:20 UTC, Jake-Carter requested changes
Looks good!  Approved pending the one comment below.

2022-11-10 20:20 UTC, Jake-Carter commented on Display/tft_st7735.c
> +    TFT_SPI_Write(&command, 1, false);
Looks good.  I just did a similar thing yesterday for the NewHaven drivers.  I would suggest adding `extern` definitions for these into the header file.

Ex:  https://github.com/Analog-Devices-MSDK/Libraries-miscDrivers/blob/fe4c6c4c61fab1d518c8e2f3ceb3033390c29996/Display/tft_st7789v.h#L152

I will change my function names to match yours.  We should also discuss standardizing the SPI write headers.  Some of the older drivers had split functions for writing a single byte vs transmitting from a buffer.

Let's merge these in for now (with the added `extern` definitions) and standardize the SPI transport layer in a later PR.

2022-11-11 14:28 UTC, Jacob-Scheiffler commented
/clang-format-run

2022-11-11 16:08 UTC, lorne-maxim approved these changes

2022-11-11 16:12 UTC, lorne-maxim commented
Ignoring the CPP lint errors for now.  They are all header-guard errors that will pass once this submodule is absorbed into the msdk repo.

2022-11-11 16:12 UTC, merged